export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const POST_ANNOUNCEMENT = "POST_ANNOUNCEMENT";
export const POST_FAILED = "POST_FAILED";
